export const ICON_MAP: Record<string, string> = {
  add: 'Plus',
  edit: 'Pencil',
  delete: 'Trash2',
  close: 'X',
  warning: 'AlertTriangle',
  info: 'Info',
  lock: 'Lock',
  arrow_back: 'ArrowLeft',
  open_in_new: 'ExternalLink',
  logout: 'LogOut',
  menu: 'Menu',
  grid_view: 'LayoutGrid',
  check_circle: 'CheckCircle',
  error: 'CircleX',
  label: 'Tag',
  article: 'FileText',
  hourglass_empty: 'Loader2',
  folder_kanban: 'FolderKanban',
  translate: 'Languages',
}
