#!/bin/bash
# Vunotek Deploy Script
# Builds Astro static site + optionally packages PHP backend for Hostinger.
#
# Usage:
#   bash deploy.sh               Build Astro only → dist/
#   bash deploy.sh --backend     Build Astro → dist/ + package backend → dist-backend/
#   bash deploy.sh --prod        Package backend only → dist-backend/ (skip frontend)
#   bash deploy.sh --no-install  Build + backend, skip composer install
#   bash deploy.sh --help        Show help

set -euo pipefail

CWD=$(pwd)
SKIP_COMPOSER=false
SKIP_FRONTEND=false
BUILD_BACKEND=false

for arg in "$@"; do
  case "$arg" in
    --prod) SKIP_FRONTEND=true; BUILD_BACKEND=true ;;
    --backend) BUILD_BACKEND=true ;;
    --no-install) SKIP_COMPOSER=true ;;
    --help|-h)
      echo "Vunotek Deploy Script"
      echo ""
      echo "  bash deploy.sh               Build Astro only → dist/"
      echo "  bash deploy.sh --backend     Build Astro → dist/ + backend → dist-backend/"
      echo "  bash deploy.sh --prod        Backend only → dist-backend/ (skip frontend)"
      echo "  bash deploy.sh --no-install  Build + backend, skip composer install"
      echo ""
      exit 0
      ;;
  esac
done

# ── Frontend Build ──────────────────────────────────────────────────

if [ "$SKIP_FRONTEND" = true ]; then
  echo "==> Modo --prod: saltando build frontend..."
else
  echo "==> Building Astro static site → dist/..."
  pnpm build
  echo "==> Frontend build complete → dist/"
fi

# ── Backend Package (optional) ──────────────────────────────────────

if [ "$BUILD_BACKEND" = true ]; then
  echo ""
  echo "==> Packaging production backend → dist-backend/..."

  # Clean previous artifacts
  rm -rf dist-backend
  mkdir -p dist-backend

  # ── PHP application directories ──
  cp -r api/admin             dist-backend/admin
  cp -r api/blog              dist-backend/blog
  cp -r api/categories        dist-backend/categories
  cp -r api/projects          dist-backend/projects
  cp -r api/imagekit          dist-backend/imagekit
  cp -r api/Config            dist-backend/Config
  cp -r api/Controllers       dist-backend/Controllers
  cp -r api/Models            dist-backend/Models
  cp -r api/Services          dist-backend/Services
  cp -r api/Traits            dist-backend/Traits

  # ── Core PHP files ──
  cp    api/bootstrap.php     dist-backend/bootstrap.php
  cp    api/install.php       dist-backend/install.php
  cp    api/send-email.php    dist-backend/send-email.php
  cp    api/calendar-handler.php dist-backend/calendar-handler.php
  cp    api/schema.sql        dist-backend/schema.sql
  cp    api/.htaccess         dist-backend/.htaccess

  # ── Config template (real config.php generated by install.php) ──
  cp    api/config.example.php dist-backend/config.example.php

  # ── Composer (install production deps) ──
  if [ "$SKIP_COMPOSER" = false ]; then
    echo "==> Installing production dependencies (--no-dev) → dist-backend/vendor/..."
    cp api/composer.json dist-backend/composer.json
    composer install --no-dev --no-interaction --optimize-autoloader --working-dir=dist-backend
  else
    echo "==> Skipping vendor install (--no-install)"
  fi

  echo "==> Backend package complete → dist-backend/"
fi

# ── Summary ─────────────────────────────────────────────────────────

echo ""
echo "============================================="
echo "  Deploy ready!"
echo ""

if [ "$BUILD_BACKEND" = true ]; then
  echo "  dist/          → Astro static frontend (subir a Netlify)"
  echo "  dist-backend/  → PHP backend (subir a Hostinger)"
  echo ""
  echo "  Upload dist-backend/* → /public_html/api/"
  echo "  Visit https://api.vunotek.com/install.php"
  echo "  Delete install.php after setup"
else
  echo "  dist/          → Astro static frontend"
  echo ""
  echo "  Upload dist/*  → Netlify (auto via git push)"
fi

echo "============================================="
