import { IK_BASE, ikSrcset } from './imagekit'

function ik(path: string): string {
  return `${IK_BASE}/${path.replace(/^\//, '')}`
}

export const IMAGES = {
  webDev: ik('hero/web-dev.webp'),
  vueCode: ik('hero/vue-code.webp'),
  workstation: ik('services/workstation.webp'),
  serverRoom: ik('services/server-room.webp'),
  dashboard: ik('portfolio/dashboard.webp'),
  shop: ik('vuno-web/products/ecomerce.webp'),
  shop_filtros: ik('vuno-web/products/ecommerce/filtros.webp'),
  shop_detalles: ik('vuno-web/products/ecommerce/detalles.webp'),
  shop_cart: ik('vuno-web/products/ecommerce/cart.webp'),
  shop_payment: ik('vuno-web/products/ecommerce/payment.webp'),
  shop_currency: ik('vuno-web/products/ecommerce/currency.webp'),
  shop_customer: ik('vuno-web/products/ecommerce/customer.webp'),
  shop_admin: ik('vuno-web/products/ecommerce/admin.webp'),
  shop_inventory: ik('vuno-web/products/ecommerce/inventory.webp'),
  shop_security: ik('vuno-web/products/ecommerce/security.webp'),
  shop_notifications: ik('vuno-web/products/ecommerce/notifications.webp'),
  shop_i18n: ik('vuno-web/products/ecommerce/i18n.webp'),
  hotel: ik('vuno-web/products/reservations.webp'),
  hotel_portada: ik('vuno-web/products/hotel/portada.webp'),
  hotel_detalles: ik('vuno-web/products/hotel/detalles.webp'),
  hotel_bookings: ik('vuno-web/products/hotel/bookings.webp'),
  hotel_receptions: ik('vuno-web/products/hotel/receptions.webp'),
  hotel_checkin: ik('vuno-web/products/hotel/checkin.webp'),
  hotel_housekeeping: ik('vuno-web/products/hotel/housekeeping.webp'),
  hotel_calendar: ik('vuno-web/products/hotel/calendar.webp'),
  hotel_guests: ik('vuno-web/products/hotel/guest.webp'),
  hotel_lifecycle: ik('vuno-web/products/hotel/lifecycle.webp'),
  hotel_admin: ik('vuno-web/products/hotel/admin.webp'),
  hotel_security: ik('vuno-web/products/hotel/security.webp'),
  hotel_notifications: ik('vuno-web/products/hotel/notifications.webp'),
  drive: ik('vuno-web/products/drive.webp'),
  drive_catalogo: ik('vuno-web/products/drive/categoriaAlquiler.webp'),
  drive_dash: ik('vuno-web/products/drive/Dashboard.webp'),
  drive_dash_rol: ik('vuno-web/products/drive/usuarios.webp'),
  drive_flota: ik('vuno-web/products/drive/flota.webp'),
  drive_sucursales: ik('vuno-web/products/drive/Sucursales.webp'),
  drive_reservas: ik('vuno-web/products/drive/Reservas.webp'),
  drive_seguros: ik('vuno-web/products/drive/seguros.webp'),
  drive_ventas: ik('vuno-web/products/drive/ventas.webp'),
  drive_clientes: ik('vuno-web/products/drive/clientes.webp'),
  drive_precios: ik('vuno-web/products/drive/precios.webp'),
  logistics: ik('vuno-web/products/logistics.webp'),
  crm: ik('vuno-web/products/crm.webp'),
  crm_inbox: ik('vuno-web/products/crm/inbox.webp'),
  crm_profiles: ik('vuno-web/products/crm/profiles.webp'),
  crm_kanban: ik('vuno-web/products/crm/kanban.webp'),
  crm_quotes: ik('vuno-web/products/crm/quotes.webp'),
  crm_attendance: ik('vuno-web/products/crm/attendance.webp'),
  crm_rbac: ik('vuno-web/products/crm/rbac.webp'),
  crm_employees: ik('vuno-web/products/crm/employees.webp'),
  crm_tasks: ik('vuno-web/products/crm/tasks.webp'),
  crm_notifications: ik('vuno-web/products/crm/notifications.webp'),
  pos: ik('vuno-web/products/Vuno-POS.webp'),
  pos_interface: ik('vuno-web/products/pos/interface.webp'),
  pos_payments: ik('vuno-web/products/pos/payments.webp'),
  pos_cashdrawer: ik('vuno-web/products/pos/cashdrawer.webp'),
  pos_offline: ik('vuno-web/products/pos/offline.webp'),
  pos_inventory: ik('vuno-web/products/pos/inventory.webp'),
  pos_transfers: ik('vuno-web/products/pos/transfers.webp'),
  pos_suppliers: ik('vuno-web/products/pos/suppliers.webp'),
  pos_dashboards: ik('vuno-web/products/pos/dashboard.webp'),
  bridge: ik('contact/bridge.webp'),
  sabores: ik('projects/saboresynuricion.webp'),
  experiencias: ik('projects/experiencias.webp')
} as const

export const IMAGE_DIMS: Record<string, { width: number; height: number }> = {
  webDev: { width: 1200, height: 800 },
  vueCode: { width: 800, height: 600 },
  workstation: { width: 800, height: 600 },
  serverRoom: { width: 800, height: 600 },
  dashboard: { width: 800, height: 600 },
  shop: { width: 800, height: 600 },
  shop_filtros: { width: 800, height: 600 },
  shop_detalles: { width: 800, height: 600 },
  shop_cart: { width: 800, height: 600 },
  shop_payment: { width: 800, height: 600 },
  shop_currency: { width: 800, height: 600 },
  shop_customer: { width: 800, height: 600 },
  shop_admin: { width: 800, height: 600 },
  shop_inventory: { width: 800, height: 600 },
  shop_security: { width: 800, height: 600 },
  shop_notifications: { width: 800, height: 600 },
  shop_i18n: { width: 800, height: 600 },
  hotel: { width: 800, height: 600 },
  hotel_portada: { width: 800, height: 600 },
  hotel_detalles: { width: 800, height: 600 },
  hotel_bookings: { width: 800, height: 600 },
  hotel_receptions: { width: 800, height: 600 },
  hotel_checkin: { width: 800, height: 600 },
  hotel_housekeeping: { width: 800, height: 600 },
  hotel_calendar: { width: 800, height: 600 },
  hotel_guests: { width: 800, height: 600 },
  hotel_lifecycle: { width: 800, height: 600 },
  hotel_admin: { width: 800, height: 600 },
  hotel_security: { width: 800, height: 600 },
  hotel_notifications: { width: 800, height: 600 },
  drive: { width: 800, height: 600 },
  drive_catalogo: { width: 800, height: 600 },
  drive_dash: { width: 800, height: 600 },
  drive_dash_rol: { width: 800, height: 600 },
  drive_flota: { width: 800, height: 600 },
  drive_sucursales: { width: 800, height: 600 },
  drive_reservas: { width: 800, height: 600 },
  drive_seguros: { width: 800, height: 600 },
  drive_ventas: { width: 800, height: 600 },
  drive_clientes: { width: 800, height: 600 },
  drive_precios: { width: 800, height: 600 },
  logistics: { width: 800, height: 600 },
  crm: { width: 800, height: 600 },
  crm_inbox: { width: 800, height: 600 },
  crm_profiles: { width: 800, height: 600 },
  crm_kanban: { width: 800, height: 600 },
  crm_quotes: { width: 800, height: 600 },
  crm_attendance: { width: 800, height: 600 },
  crm_rbac: { width: 800, height: 600 },
  crm_employees: { width: 800, height: 600 },
  crm_tasks: { width: 800, height: 600 },
  crm_notifications: { width: 800, height: 600 },
  pos: { width: 800, height: 600 },
  pos_interface: { width: 800, height: 600 },
  pos_payments: { width: 800, height: 600 },
  pos_cashdrawer: { width: 800, height: 600 },
  pos_offline: { width: 800, height: 600 },
  pos_inventory: { width: 800, height: 600 },
  pos_transfers: { width: 800, height: 600 },
  pos_suppliers: { width: 800, height: 600 },
  pos_dashboards: { width: 800, height: 600 },
  bridge: { width: 1200, height: 800 },
  sabores: { width: 800, height: 600 },
  experiencias: { width: 800, height: 600 }
} as const

const IMAGE_PATHS: Record<string, string> = {
  webDev: 'hero/web-dev.webp',
  vueCode: 'hero/vue-code.webp',
  workstation: 'services/workstation.webp',
  serverRoom: 'services/server-room.webp',
  dashboard: 'portfolio/dashboard.webp',
  shop: 'vuno-web/products/ecomerce.webp',
  shop_filtros: 'vuno-web/products/ecommerce/filtros.webp',
  shop_detalles: 'vuno-web/products/ecommerce/detalles.webp',
  shop_cart: 'vuno-web/products/ecommerce/cart.webp',
  shop_payment: 'vuno-web/products/ecommerce/payment.webp',
  shop_currency: 'vuno-web/products/ecommerce/currency.webp',
  shop_customer: 'vuno-web/products/ecommerce/customer.webp',
  shop_admin: 'vuno-web/products/ecommerce/admin.webp',
  shop_inventory: 'vuno-web/products/ecommerce/inventory.webp',
  shop_security: 'vuno-web/products/ecommerce/security.webp',
  shop_notifications: 'vuno-web/products/ecommerce/notifications.webp',
  shop_i18n: 'vuno-web/products/ecommerce/i18n.webp',
  hotel: 'vuno-web/products/reservations.webp',
  hotel_portada: 'vuno-web/products/hotel/portada.webp',
  hotel_detalles: 'vuno-web/products/hotel/detalles.webp',
  hotel_bookings: 'vuno-web/products/hotel/bookings.webp',
  hotel_receptions: 'vuno-web/products/hotel/receptions.webp',
  hotel_checkin: 'vuno-web/products/hotel/checkin.webp',
  hotel_housekeeping: 'vuno-web/products/hotel/housekeeping.webp',
  hotel_calendar: 'vuno-web/products/hotel/calendar.webp',
  hotel_guests: 'vuno-web/products/hotel/guest.webp',
  hotel_lifecycle: 'vuno-web/products/hotel/lifecycle.webp',
  hotel_admin: 'vuno-web/products/hotel/admin.webp',
  hotel_security: 'vuno-web/products/hotel/security.webp',
  hotel_notifications: 'vuno-web/products/hotel/notifications.webp',
  drive: 'vuno-web/products/drive.webp',
  drive_catalogo: 'vuno-web/products/drive/categoriaAlquiler.webp',
  drive_dash: 'vuno-web/products/drive/Dashboard.webp',
  drive_dash_rol: 'vuno-web/products/drive/usuarios.webp',
  drive_flota: 'vuno-web/products/drive/flota.webp',
  drive_sucursales: 'vuno-web/products/drive/Sucursales.webp',
  drive_reservas: 'vuno-web/products/drive/Reservas.webp',
  drive_seguros: 'vuno-web/products/drive/seguros.webp',
  drive_ventas: 'vuno-web/products/drive/ventas.webp',
  drive_clientes: 'vuno-web/products/drive/clientes.webp',
  drive_precios: 'vuno-web/products/drive/precios.webp',
  logistics: 'vuno-web/products/logistics.webp',
  crm: 'vuno-web/products/crm.webp',
  crm_inbox: 'vuno-web/products/crm/inbox.webp',
  crm_profiles: 'vuno-web/products/crm/profiles.webp',
  crm_kanban: 'vuno-web/products/crm/kanban.webp',
  crm_quotes: 'vuno-web/products/crm/quotes.webp',
  crm_attendance: 'vuno-web/products/crm/attendance.webp',
  crm_rbac: 'vuno-web/products/crm/rbac.webp',
  crm_employees: 'vuno-web/products/crm/employees.webp',
  crm_tasks: 'vuno-web/products/crm/tasks.webp',
  crm_notifications: 'vuno-web/products/crm/notifications.webp',
  pos: 'vuno-web/products/Vuno-POS.webp',
  pos_interface: 'vuno-web/products/pos/interface.webp',
  pos_payments: 'vuno-web/products/pos/payments.webp',
  pos_cashdrawer: 'vuno-web/products/pos/cashdrawer.webp',
  pos_offline: 'vuno-web/products/pos/offline.webp',
  pos_inventory: 'vuno-web/products/pos/inventory.webp',
  pos_transfers: 'vuno-web/products/pos/transfers.webp',
  pos_suppliers: 'vuno-web/products/pos/suppliers.webp',
  pos_dashboards: 'vuno-web/products/pos/dashboard.webp',
  bridge: 'contact/bridge.webp',
  sabores: 'projects/saboresynuricion.webp',
  experiencias: 'projects/experiencias.webp'
}

export function getResponsiveAttrs(key: string): { srcset: string; sizes: string } | null {
  const path = IMAGE_PATHS[key]
  if (!path) return null
  return {
    srcset: ikSrcset(path, [400, 800, 1200]),
    sizes: '(max-width: 768px) 100vw, (max-width: 1200px) 80vw, 800px'
  }
}
