name: Deploy vunotek site  to Hostinger
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v6
        with:
          cache: true
          cache_dependency_path: pnpm-lock.yaml

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - run: pnpm install && pnpm build
      
      - uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
